import Head from 'next/head'
import Image from 'next/image'
import NavBar from '../components/NavBar'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <main>
        <h1>My Perfect To-Do APP</h1>
      </main>
    </div>
  )
}
